import {
  Wifi,
  Waves,
  Coffee,
  Car,
  ShieldCheck,
  Sun,
  Users,
  Heart,
  Baby,
  Compass,
  Plane,
  MapPin,
  Clock3,
} from "lucide-react";

export const siteData = {
  brand: {
    name: "Casa Brisa del Mar",
    tagline: "Modern tropical stays near Cancun",
    whatsappNumber: "+52 998 000 0000",
    email: "hello@casabrisadelmar.com",
  },
  currencies: {
    USD: { symbol: "$", rate: 1, label: "USD" },
    MXN: { symbol: "$", rate: 16.7, label: "MXN" },
    EUR: { symbol: "€", rate: 0.92, label: "EUR" },
    CAD: { symbol: "C$", rate: 1.36, label: "CAD" },
    GBP: { symbol: "£", rate: 0.79, label: "GBP" },
    BRL: { symbol: "R$", rate: 4.95, label: "BRL" },
  },
  supportedLanguages: [
    { code: "en", label: "English" },
    { code: "es", label: "Español" },
    { code: "fr", label: "Français" },
    { code: "pt", label: "Português" },
  ],
  heroImages: [
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1400&q=80",
    "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=900&q=80",
  ],
  highlights: [
    "Direct booking with the host",
    "Near beaches, day trips, and local dining",
    "Fast Wi-Fi and warm hospitality",
    "Great for couples, families, solo travelers, and small groups",
  ],
  amenities: [
    { label: "High-speed Wi-Fi", icon: Wifi },
    { label: "Private pool", icon: Waves },
    { label: "Breakfast included", icon: Coffee },
    { label: "Free parking", icon: Car },
    { label: "Safe & secure", icon: ShieldCheck },
    { label: "Sunny Caribbean vibe", icon: Sun },
  ],
  rooms: [
    {
      id: "room-1",
      name: "The Ocean Room",
      priceUSD: 85,
      sleeps: "2 guests",
      bed: "1 King bed",
      size: "28 m²",
      season: "High demand",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
      features: ["Private terrace", "Ocean view", "Rain shower", "Air conditioning"],
      status: "Available",
      badge: "Most popular",
      descriptions: {
        en: "Wake up to soft ocean breezes through the white curtains. The Ocean Room features a private terrace with a partial sea view, premium linens, and a modern en-suite bathroom.",
        es: "Despierta con brisas suaves del mar. La habitación Ocean ofrece terraza privada, vista parcial al mar, sábanas premium y baño moderno.",
        fr: "Réveillez-vous avec une douce brise marine. La chambre Ocean propose une terrasse privée, une vue partielle sur la mer et une salle de bain moderne.",
        pt: "Acorde com a brisa do mar. O quarto Ocean tem terraço privativo, vista parcial do mar, roupa de cama premium e banheiro moderno.",
      },
    },
    {
      id: "room-2",
      name: "The Garden Suite",
      priceUSD: 110,
      sleeps: "4 guests",
      bed: "1 King + 1 sofa bed",
      size: "42 m²",
      season: "Family favorite",
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80",
      features: ["Pool access", "Garden view", "Kitchenette", "Extra space"],
      status: "Available",
      badge: "Best for families",
      descriptions: {
        en: "The largest space in the house, surrounded by lush tropical plants. Perfect for families or friends who want more room and easy access to the outdoor areas.",
        es: "El espacio más amplio de la casa, rodeado de plantas tropicales. Ideal para familias o amigos que quieren más espacio y acceso a las áreas exteriores.",
        fr: "Le plus grand espace de la maison, entouré de plantes tropicales. Parfait pour les familles ou les amis souhaitant plus d’espace.",
        pt: "O maior espaço da casa, cercado por plantas tropicais. Perfeito para famílias ou amigos que querem mais espaço e acesso às áreas externas.",
      },
    },
    {
      id: "room-3",
      name: "The Rooftop Loft",
      priceUSD: 95,
      sleeps: "2 guests",
      bed: "1 Queen bed",
      size: "32 m²",
      season: "Romantic pick",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
      features: ["Private rooftop", "Panoramic view", "Premium linens", "Hammock"],
      status: "Available",
      badge: "Most romantic",
      descriptions: {
        en: "An intimate hideaway on the top floor with a private rooftop deck where you can stargaze at night or sip your morning coffee above the palm trees.",
        es: "Un refugio íntimo en la planta alta con terraza privada para mirar las estrellas o tomar café entre las palmeras.",
        fr: "Un refuge intime au dernier étage avec terrasse privée pour admirer les étoiles ou prendre un café au-dessus des palmiers.",
        pt: "Um refúgio íntimo no último andar com terraço privativo para ver as estrelas ou tomar café acima das palmeiras.",
      },
    },
  ],
  travelerTypes: [
    { title: "Solo trips", icon: Compass, copy: "Quiet, safe, personal, and easy to navigate — ideal for solo travelers who want comfort without the resort feel." },
    { title: "Couples", icon: Heart, copy: "Great for romantic getaways, beach mornings, sunset dinners, and slow tropical days together." },
    { title: "Family trips", icon: Baby, copy: "Room options and outdoor space make it easier for families to settle in and enjoy the area." },
    { title: "Small groups", icon: Users, copy: "Perfect for friend groups, wedding guests, retreat weekends, and shared stays near Cancun." },
  ],
  attractions: [
    { name: "Nearby beaches", type: "Beach", time: "5–15 min", copy: "Easy beach access for swimming, relaxing, and sunset walks.", icon: Waves },
    { name: "Downtown Cancun dining", type: "Food & nightlife", time: "15–25 min", copy: "Local restaurants, tacos, cafes, and nightlife within easy reach.", icon: Coffee },
    { name: "Isla Mujeres ferry", type: "Day trip", time: "20–30 min", copy: "An easy add-on for beach clubs, snorkeling, and a full-day island escape.", icon: Plane },
    { name: "Cenotes & nature spots", type: "Adventure", time: "30–60 min", copy: "Perfect for guests who want a more natural and memorable Yucatán experience.", icon: Sun },
    { name: "Shopping & essentials", type: "Convenience", time: "10–20 min", copy: "Groceries, pharmacies, and practical stops close enough for easy stays.", icon: MapPin },
    { name: "Airport access", type: "Travel", time: "25–40 min", copy: "Convenient enough for weekend stays, longer vacations, and smooth arrivals.", icon: Clock3 },
  ],
  neighborhood: [
    { title: "Quiet home base", copy: "A calmer stay than the hotel zone, with easier mornings, local rhythm, and less noise." },
    { title: "Good food nearby", copy: "Close to tacos, seafood, breakfast spots, and casual dinner places guests actually enjoy." },
    { title: "Easy day trips", copy: "Useful for beach hopping, cenote visits, ferry rides, and exploring more of Quintana Roo." },
    { title: "Practical location", copy: "Simple access to transport, groceries, airport transfers, and the essentials guests need." },
  ],
  seasons: [
    { name: "Low season", months: "May – June", sampleRateUSD: 75, copy: "Better value and more flexibility for longer stays and slower travel." },
    { name: "Shoulder season", months: "September – November", sampleRateUSD: 90, copy: "Balanced weather, better availability, and a calmer pace than peak holiday periods." },
    { name: "Peak season", months: "December – April", sampleRateUSD: 125, copy: "Best time to book early. Holiday and winter demand usually pushes rates higher." },
  ],
  availabilityMonths: [
    {
      name: "May",
      statuses: [
        { label: "Ocean Room", value: "Good" },
        { label: "Garden Suite", value: "Good" },
        { label: "Rooftop Loft", value: "Limited" },
      ],
    },
    {
      name: "June",
      statuses: [
        { label: "Ocean Room", value: "Good" },
        { label: "Garden Suite", value: "Limited" },
        { label: "Rooftop Loft", value: "Good" },
      ],
    },
    {
      name: "July",
      statuses: [
        { label: "Ocean Room", value: "Limited" },
        { label: "Garden Suite", value: "Good" },
        { label: "Rooftop Loft", value: "Limited" },
      ],
    },
    {
      name: "August",
      statuses: [
        { label: "Ocean Room", value: "Busy" },
        { label: "Garden Suite", value: "Limited" },
        { label: "Rooftop Loft", value: "Busy" },
      ],
    },
    {
      name: "September",
      statuses: [
        { label: "Ocean Room", value: "Good" },
        { label: "Garden Suite", value: "Good" },
        { label: "Rooftop Loft", value: "Good" },
      ],
    },
  ],
  gallery: [
    "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
  ],
  testimonials: [
    { name: "Sarah (USA)", text: "This felt way more personal than a resort. Super clean, great host, and easy booking.", rating: 5 },
    { name: "Luis (Mexico)", text: "Muy cómodo, excelente ubicación y muy buena atención.", rating: 5 },
    { name: "Claire (France)", text: "Beautiful place, peaceful and close to everything. Would stay again.", rating: 5 },
  ],
  addOns: [
    { title: "Airport pickup", price: "$40", desc: "Private pickup from Cancun airport" },
    { title: "Grocery setup", price: "$25", desc: "Fridge stocked before arrival" },
    { title: "Local tours", price: "$60+", desc: "Cenotes, island trips, excursions" },
    { title: "Romantic setup", price: "$50", desc: "Decor + wine for couples" },
  ],
};

export const translations = {
  en: {
    navRooms: "Rooms",
    navGallery: "Gallery",
    navAttractions: "Attractions",
    navReviews: "Reviews",
    navBook: "Book",
    near: "Near Cancun, Mexico",
    heroTitle: "A modern tropical stay near Cancun that feels easy, warm, and unforgettable.",
    heroCopy: "Private rooms, direct booking, local hosting, and a calm Caribbean vibe — designed for travelers who want something more personal than a big resort.",
    viewRooms: "View rooms",
    requestBooking: "Request a booking",
    directBooking: "Direct booking — no platform fees",
    ratings: "4.98 rating · 84 reviews",
    multiReady: "Multi-language + currency ready",
    roomsEyebrow: "Stay",
    roomsTitle: "Choose the room that fits your trip",
    roomsCopy: "A simpler room-first layout with clear details, better photos, and less clutter than a typical rental site.",
    startingFrom: "Starting from",
    requestThisRoom: "Request this room",
    amenitiesEyebrow: "Included",
    amenitiesTitle: "Everything guests usually ask about, upfront",
    amenitiesCopy: "Make the important details obvious so guests can say yes faster.",
    galleryEyebrow: "Gallery",
    galleryTitle: "Bright photos. Clean layout. Strong first impression.",
    galleryCopy: "Good photos do most of the selling. Keep the design simple and let the home feel real.",
    tripEyebrow: "Perfect for",
    tripTitle: "Different kinds of trips, one calm home base",
    tripCopy: "Help guests picture themselves here by speaking directly to the kind of stay they want.",
    attractionsEyebrow: "Nearby",
    attractionsTitle: "Easy access to the best of Cancun and the coast",
    attractionsCopy: "This section helps turn interest into booking by showing guests what they can enjoy nearby.",
    neighborhoodEyebrow: "Neighborhood",
    neighborhoodTitle: "Show guests what it feels like to stay here",
    neighborhoodCopy: "A good location section helps people understand the vibe, not just the map pin.",
    seasonEyebrow: "Pricing",
    seasonTitle: "Simple seasonal pricing guidance",
    seasonCopy: "A cleaner way to show guests that rates can change across the year.",
    sampleNightlyRate: "Sample nightly rate",
    availabilityEyebrow: "Availability",
    availabilityTitle: "A simple availability preview",
    availabilityCopy: "This is not live inventory yet — it just gives guests a fast sense of booking demand.",
    reviewsEyebrow: "Reviews",
    testimonialsTitle: "What guests say",
    reviewsCopy: "Social proof builds trust fast.",
    addOnsEyebrow: "Add-ons",
    addOnsTitle: "Enhance your stay",
    addOnsCopy: "Easy ways to increase booking value over time.",
    mapEyebrow: "Map",
    locationTitle: "Location",
    locationCopy: "Near Cancun, with easy access to beaches, day trips, restaurants, and airport connections.",
    bookingEyebrow: "Book direct",
    bookingTitle: "Keep bookings simple now, upgrade later",
    bookingCopy: "Version 1 should collect booking requests by form, email, or WhatsApp.",
    chooseDates: "Choose dates",
    chooseDatesCopy: "Guests share preferred check-in and check-out dates.",
    pickRoom: "Pick a room",
    pickRoomCopy: "They select the room that fits their stay best.",
    confirmFast: "Confirm quickly",
    confirmFastCopy: "The host responds by WhatsApp or email.",
    requestStay: "Request a stay",
    formIntro: "This can stay simple for now. Later it can connect to Netlify Forms or a booking backend.",
    fullName: "Full name",
    email: "Email",
    checkIn: "Check-in",
    checkOut: "Check-out",
    selectRoom: "Select a room",
    questions: "Questions, arrival time, number of guests...",
    sendBooking: "Send booking request",
    socialEyebrow: "Social",
    socialTitle: "Add more trust later with Instagram and fresh guest content",
    socialCopy: "Once the real property photos and guest stays start coming in, this section can point visitors to Instagram, recent updates, or story highlights.",
    footerTag: "Built for direct bookings — no platform fees.",
  },
  es: {
    navRooms: "Habitaciones",
    navGallery: "Galería",
    navAttractions: "Atracciones",
    navReviews: "Reseñas",
    navBook: "Reservar",
    near: "Cerca de Cancún, México",
    heroTitle: "Una estadía tropical moderna cerca de Cancún, fácil, cálida e inolvidable.",
    heroCopy: "Habitaciones privadas, reservas directas, atención local y un ambiente caribeño tranquilo.",
    viewRooms: "Ver habitaciones",
    requestBooking: "Solicitar reserva",
    directBooking: "Reserva directa — sin comisiones",
    ratings: "Calificación 4.98 · 84 reseñas",
    multiReady: "Listo para varios idiomas y monedas",
    roomsEyebrow: "Hospedaje",
    roomsTitle: "Elige la habitación ideal para tu viaje",
    roomsCopy: "Un diseño simple y enfocado en habitaciones con detalles claros y mejores fotos.",
    startingFrom: "Desde",
    requestThisRoom: "Solicitar esta habitación",
    amenitiesEyebrow: "Incluido",
    amenitiesTitle: "Todo lo importante, al frente",
    amenitiesCopy: "Muestra los detalles clave para que sea más fácil reservar.",
    galleryEyebrow: "Galería",
    galleryTitle: "Fotos luminosas. Diseño limpio. Gran impresión.",
    galleryCopy: "Las buenas fotos hacen gran parte de la venta.",
    tripEyebrow: "Ideal para",
    tripTitle: "Diferentes tipos de viaje, una base tranquila",
    tripCopy: "Ayuda a los huéspedes a imaginarse aquí según el tipo de estancia.",
    attractionsEyebrow: "Cerca",
    attractionsTitle: "Acceso fácil a lo mejor de Cancún y la costa",
    attractionsCopy: "Esta sección ayuda a convertir interés en reservas.",
    neighborhoodEyebrow: "Zona",
    neighborhoodTitle: "Muestra cómo se siente alojarse aquí",
    neighborhoodCopy: "Una buena sección de ubicación explica el ambiente, no solo el mapa.",
    seasonEyebrow: "Precios",
    seasonTitle: "Guía simple de precios por temporada",
    seasonCopy: "Una forma clara de mostrar que las tarifas cambian durante el año.",
    sampleNightlyRate: "Tarifa por noche de ejemplo",
    availabilityEyebrow: "Disponibilidad",
    availabilityTitle: "Vista previa simple de disponibilidad",
    availabilityCopy: "Aún no es inventario en vivo — solo da una idea rápida de la demanda.",
    reviewsEyebrow: "Reseñas",
    testimonialsTitle: "Lo que dicen los huéspedes",
    reviewsCopy: "La prueba social genera confianza rápido.",
    addOnsEyebrow: "Extras",
    addOnsTitle: "Mejora tu estancia",
    addOnsCopy: "Formas fáciles de aumentar el valor de cada reserva.",
    mapEyebrow: "Mapa",
    locationTitle: "Ubicación",
    locationCopy: "Cerca de Cancún, con acceso fácil a playas, excursiones, restaurantes y aeropuerto.",
    bookingEyebrow: "Reserva directa",
    bookingTitle: "Mantén las reservas simples ahora",
    bookingCopy: "La versión 1 debe recibir solicitudes por formulario, correo o WhatsApp.",
    chooseDates: "Elegir fechas",
    chooseDatesCopy: "Los huéspedes comparten sus fechas de entrada y salida.",
    pickRoom: "Elegir habitación",
    pickRoomCopy: "Seleccionan la habitación ideal para su viaje.",
    confirmFast: "Confirmar rápido",
    confirmFastCopy: "La anfitriona responde por WhatsApp o correo.",
    requestStay: "Solicitar estancia",
    formIntro: "Por ahora puede seguir siendo simple. Después se puede conectar a Netlify Forms.",
    fullName: "Nombre completo",
    email: "Correo electrónico",
    checkIn: "Entrada",
    checkOut: "Salida",
    selectRoom: "Selecciona una habitación",
    questions: "Preguntas, hora de llegada, número de huéspedes...",
    sendBooking: "Enviar solicitud",
    socialEyebrow: "Social",
    socialTitle: "Añade más confianza después con Instagram y contenido real",
    socialCopy: "Cuando ya tengan fotos reales y más huéspedes, esta sección puede apuntar a Instagram o historias recientes.",
    footerTag: "Hecho para reservas directas — sin comisiones.",
  },
  fr: {
    navRooms: "Chambres",
    navGallery: "Galerie",
    navAttractions: "Attractions",
    navReviews: "Avis",
    navBook: "Réserver",
    near: "Près de Cancún, Mexique",
    heroTitle: "Un séjour tropical moderne près de Cancún, simple, chaleureux et inoubliable.",
    heroCopy: "Chambres privées, réservation directe, accueil local et ambiance caribéenne paisible.",
    viewRooms: "Voir les chambres",
    requestBooking: "Demander une réservation",
    directBooking: "Réservation directe — sans frais",
    ratings: "Note 4,98 · 84 avis",
    multiReady: "Prêt pour plusieurs langues et devises",
    roomsEyebrow: "Séjour",
    roomsTitle: "Choisissez la chambre idéale pour votre voyage",
    roomsCopy: "Une présentation simple, centrée sur les chambres, avec des détails clairs.",
    startingFrom: "À partir de",
    requestThisRoom: "Demander cette chambre",
    amenitiesEyebrow: "Inclus",
    amenitiesTitle: "Tout ce que les voyageurs demandent souvent",
    amenitiesCopy: "Affichez clairement les points importants.",
    galleryEyebrow: "Galerie",
    galleryTitle: "Photos lumineuses. Mise en page épurée.",
    galleryCopy: "De bonnes photos font une grande partie du travail.",
    tripEyebrow: "Parfait pour",
    tripTitle: "Différents styles de voyage, une base paisible",
    tripCopy: "Aidez les voyageurs à se projeter ici.",
    attractionsEyebrow: "À proximité",
    attractionsTitle: "Accès facile au meilleur de Cancún et de la côte",
    attractionsCopy: "Cette section aide à transformer l’intérêt en réservation.",
    neighborhoodEyebrow: "Quartier",
    neighborhoodTitle: "Montrez ce que l’on ressent en séjournant ici",
    neighborhoodCopy: "Une bonne section emplacement explique l’ambiance, pas seulement le point sur la carte.",
    seasonEyebrow: "Tarifs",
    seasonTitle: "Guide simple des prix selon la saison",
    seasonCopy: "Une façon claire de montrer que les tarifs changent au fil de l’année.",
    sampleNightlyRate: "Tarif indicatif par nuit",
    availabilityEyebrow: "Disponibilité",
    availabilityTitle: "Aperçu simple des disponibilités",
    availabilityCopy: "Ce n’est pas encore un stock en temps réel — cela donne juste une idée rapide de la demande.",
    reviewsEyebrow: "Avis",
    testimonialsTitle: "Avis des voyageurs",
    reviewsCopy: "La preuve sociale inspire rapidement confiance.",
    addOnsEyebrow: "Extras",
    addOnsTitle: "Améliorez votre séjour",
    addOnsCopy: "Des moyens simples d’augmenter la valeur de chaque réservation.",
    mapEyebrow: "Carte",
    locationTitle: "Emplacement",
    locationCopy: "Près de Cancún, avec un accès facile aux plages, excursions et à l’aéroport.",
    bookingEyebrow: "Réserver en direct",
    bookingTitle: "Gardez la réservation simple maintenant",
    bookingCopy: "La version 1 doit recueillir des demandes par formulaire, e-mail ou WhatsApp.",
    chooseDates: "Choisir les dates",
    chooseDatesCopy: "Les voyageurs partagent leurs dates d’arrivée et de départ.",
    pickRoom: "Choisir une chambre",
    pickRoomCopy: "Ils sélectionnent la chambre la plus adaptée.",
    confirmFast: "Confirmer rapidement",
    confirmFastCopy: "L’hôte répond par WhatsApp ou par e-mail.",
    requestStay: "Demander un séjour",
    formIntro: "Cela peut rester simple pour l’instant. Plus tard, le formulaire pourra être relié à Netlify Forms.",
    fullName: "Nom complet",
    email: "E-mail",
    checkIn: "Arrivée",
    checkOut: "Départ",
    selectRoom: "Choisissez une chambre",
    questions: "Questions, heure d’arrivée, nombre de voyageurs...",
    sendBooking: "Envoyer la demande",
    socialEyebrow: "Social",
    socialTitle: "Ajoutez plus de confiance plus tard avec Instagram et du contenu réel",
    socialCopy: "Quand vous aurez de vraies photos et plus de séjours, cette section pourra pointer vers Instagram ou des mises à jour récentes.",
    footerTag: "Conçu pour la réservation directe — sans frais.",
  },
  pt: {
    navRooms: "Quartos",
    navGallery: "Galeria",
    navAttractions: "Atrações",
    navReviews: "Avaliações",
    navBook: "Reservar",
    near: "Perto de Cancún, México",
    heroTitle: "Uma estadia tropical moderna perto de Cancún, fácil, acolhedora e inesquecível.",
    heroCopy: "Quartos privativos, reserva direta, atendimento local e clima caribenho tranquilo.",
    viewRooms: "Ver quartos",
    requestBooking: "Solicitar reserva",
    directBooking: "Reserva direta — sem taxas",
    ratings: "Nota 4,98 · 84 avaliações",
    multiReady: "Pronto para vários idiomas e moedas",
    roomsEyebrow: "Hospedagem",
    roomsTitle: "Escolha o quarto ideal para sua viagem",
    roomsCopy: "Um layout simples e focado nos quartos, com detalhes claros.",
    startingFrom: "A partir de",
    requestThisRoom: "Solicitar este quarto",
    amenitiesEyebrow: "Incluído",
    amenitiesTitle: "Tudo o que os hóspedes costumam perguntar",
    amenitiesCopy: "Mostre os detalhes importantes com clareza.",
    galleryEyebrow: "Galeria",
    galleryTitle: "Fotos iluminadas. Layout limpo.",
    galleryCopy: "Boas fotos fazem grande parte da venda.",
    tripEyebrow: "Ideal para",
    tripTitle: "Diferentes tipos de viagem, uma base tranquila",
    tripCopy: "Ajude o hóspede a se imaginar aqui.",
    attractionsEyebrow: "Por perto",
    attractionsTitle: "Acesso fácil ao melhor de Cancún e da costa",
    attractionsCopy: "Esta seção ajuda a transformar interesse em reserva.",
    neighborhoodEyebrow: "Região",
    neighborhoodTitle: "Mostre como é se hospedar aqui",
    neighborhoodCopy: "Uma boa seção de localização explica o clima do lugar, não só o mapa.",
    seasonEyebrow: "Preços",
    seasonTitle: "Guia simples de preços por temporada",
    seasonCopy: "Uma forma clara de mostrar que as tarifas mudam ao longo do ano.",
    sampleNightlyRate: "Tarifa noturna de exemplo",
    availabilityEyebrow: "Disponibilidade",
    availabilityTitle: "Prévia simples de disponibilidade",
    availabilityCopy: "Ainda não é inventário ao vivo — apenas dá uma noção rápida da procura.",
    reviewsEyebrow: "Avaliações",
    testimonialsTitle: "O que os hóspedes dizem",
    reviewsCopy: "Prova social gera confiança rapidamente.",
    addOnsEyebrow: "Extras",
    addOnsTitle: "Melhore sua estadia",
    addOnsCopy: "Maneiras fáceis de aumentar o valor de cada reserva.",
    mapEyebrow: "Mapa",
    locationTitle: "Localização",
    locationCopy: "Perto de Cancún, com fácil acesso a praias, passeios, restaurantes e aeroporto.",
    bookingEyebrow: "Reserve direto",
    bookingTitle: "Mantenha a reserva simples agora",
    bookingCopy: "A versão 1 deve receber pedidos por formulário, e-mail ou WhatsApp.",
    chooseDates: "Escolher datas",
    chooseDatesCopy: "Os hóspedes enviam datas de check-in e check-out.",
    pickRoom: "Escolher quarto",
    pickRoomCopy: "Eles selecionam o quarto ideal para a estadia.",
    confirmFast: "Confirmar rápido",
    confirmFastCopy: "A anfitriã responde por WhatsApp ou e-mail.",
    requestStay: "Solicitar estadia",
    formIntro: "Pode continuar simples por enquanto. Depois, isso pode se conectar ao Netlify Forms.",
    fullName: "Nome completo",
    email: "E-mail",
    checkIn: "Check-in",
    checkOut: "Check-out",
    selectRoom: "Selecione um quarto",
    questions: "Perguntas, horário de chegada, número de hóspedes...",
    sendBooking: "Enviar solicitação",
    socialEyebrow: "Social",
    socialTitle: "Adicione mais confiança depois com Instagram e conteúdo real",
    socialCopy: "Quando houver fotos reais e mais hóspedes, esta seção pode apontar para Instagram ou novidades recentes.",
    footerTag: "Feito para reservas diretas — sem taxas.",
  },
};
