import {
  Wifi,
  Waves,
  Coffee,
  Car,
  ShieldCheck,
  Sun,
  Users,
  Heart,
  Baby,
  Compass,
  Plane,
  MapPin,
  Clock3,
  BadgeCheck,
  Luggage,
  Utensils,
  Clock,
  CircleHelp,
  Sailboat,
  Fish,
  Trees,
  Camera,
  MountainSnow,
  Bike,
} from "lucide-react";

export const siteData = {
  brand: {
    name: "Casa Brisa del Mar",
    locationShort: "Near Cancun, Mexico",
    tagline: "Modern tropical stays near Cancun",
    whatsappNumber: "+52 998 000 0000",
    email: "hello@casabrisadelmar.com",
    instagram: "#",
  },
  currencies: {
    USD: { symbol: "$", rate: 1, label: "USD" },
    MXN: { symbol: "$", rate: 16.7, label: "MXN" },
    EUR: { symbol: "€", rate: 0.92, label: "EUR" },
    CAD: { symbol: "C$", rate: 1.36, label: "CAD" },
    GBP: { symbol: "£", rate: 0.79, label: "GBP" },
    BRL: { symbol: "R$", rate: 4.95, label: "BRL" },
  },
  supportedLanguages: [
    { code: "en", label: "English" },
    { code: "es", label: "Español" },
    { code: "fr", label: "Français" },
    { code: "pt", label: "Português" },
  ],
  heroImages: [
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1600&q=80",
  ],
  homeStats: [
    { value: "3", label: "Private rooms" },
    { value: "10 min", label: "From the beach" },
    { value: "Direct", label: "Book with the host" },
  ],
  specials: [
    { badge: "Popular", title: "Direct booking rates" },
    { badge: "Flexible", title: "Longer stay options" },
    { badge: "Local", title: "Trips and recommendations" },
  ],
  infoStrip: [
    { icon: BadgeCheck, label: "Direct booking with the host" },
    { icon: Clock, label: "Fast response on WhatsApp" },
    { icon: Luggage, label: "Good for short and extended stays" },
    { icon: Utensils, label: "Near local dining and essentials" },
  ],
  amenities: [
    { label: "High-speed Wi-Fi", icon: Wifi },
    { label: "Private pool", icon: Waves },
    { label: "Breakfast included", icon: Coffee },
    { label: "Free parking", icon: Car },
    { label: "Safe & secure", icon: ShieldCheck },
    { label: "Sunny Caribbean vibe", icon: Sun },
  ],
  rooms: [
    {
      id: "room-1",
      name: "The Ocean Room",
      priceUSD: 85,
      sleeps: "2 guests",
      bed: "1 King bed",
      size: "28 m²",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
      features: ["Private terrace", "Ocean view", "Rain shower", "Air conditioning"],
      status: "Available",
      badge: "Most popular",
      description: "Wake up to soft ocean breezes, a bright interior, and a private terrace with a relaxed coastal feel.",
    },
    {
      id: "room-2",
      name: "The Garden Suite",
      priceUSD: 110,
      sleeps: "4 guests",
      bed: "1 King + 1 sofa bed",
      size: "42 m²",
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80",
      features: ["Pool access", "Garden view", "Kitchenette", "Extra space"],
      status: "Available",
      badge: "Best for families",
      description: "A larger suite framed by tropical greenery, ideal for families and longer stays with extra comfort.",
    },
    {
      id: "room-3",
      name: "The Rooftop Loft",
      priceUSD: 95,
      sleeps: "2 guests",
      bed: "1 Queen bed",
      size: "32 m²",
      image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",
      features: ["Private rooftop", "Open-air feel", "Premium linens", "Hammock"],
      status: "Available",
      badge: "Most romantic",
      description: "An intimate top-floor retreat with a private rooftop setting made for slower mornings and sunset evenings.",
    },
  ],
  travelerTypes: [
    { title: "Solo trips", icon: Compass, copy: "Quiet, personal, and easy to navigate." },
    { title: "Couples", icon: Heart, copy: "A relaxed setting for beach mornings and sunset dinners." },
    { title: "Family trips", icon: Baby, copy: "Room options and outdoor space that make family stays easier." },
    { title: "Small groups", icon: Users, copy: "A comfortable base for shared stays near Cancun." },
  ],
  experiences: [
    {
      title: "Cenote caves and freshwater swimming",
      category: "Nature + adventure",
      time: "Half day to full day",
      icon: Trees,
      level: "Moderate",
      bestFor: "Nature lovers, couples, small groups",
      image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1200&q=80",
      summary: "A classic Yucatán experience built around freshwater cenotes, cave swimming, jungle settings, and cooler, shaded scenery.",
      highlights: ["Underground cave feel", "Freshwater swimming", "Easy tour add-on", "Great photo moments"],
    },
    {
      title: "Boat day to Isla Mujeres",
      category: "Island + water",
      time: "Full day",
      icon: Sailboat,
      level: "Easy",
      bestFor: "First-time visitors, groups, beach lovers",
      image: "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80",
      summary: "A relaxed island-style day with boat transport, bright turquoise water, beach time, and a slower pace than the main hotel zone.",
      highlights: ["Boat ride", "Beach clubs", "Snorkeling options", "Easy day trip"],
    },
    {
      title: "Nichupté lagoon kayaking or paddleboarding",
      category: "Scenic + active",
      time: "2–3 hours",
      icon: Waves,
      level: "Light",
      bestFor: "Active travelers, couples, sunrise or sunset outings",
      image: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?auto=format&fit=crop&w=1200&q=80",
      summary: "A quieter side of Cancun with mangroves, water, and a more local outdoor feel away from the busier beach strip.",
      highlights: ["Sunrise or sunset", "Wildlife views", "Short outing", "Low-stress activity"],
    },
    {
      title: "Playa Delfines scenic stop and coastal walk",
      category: "Easy sightseeing",
      time: "1–2 hours",
      icon: Camera,
      level: "Very easy",
      bestFor: "First-time visitors, families, quick scenic plans",
      image: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=80",
      summary: "A classic Cancun view with open beach, big sky, and one of the easiest scenic stops to fit into a relaxed day.",
      highlights: ["Iconic beach views", "Low effort", "Great photos", "Easy taxi stop"],
    },
    {
      title: "Snorkeling and reef day",
      category: "Ocean activity",
      time: "Half day",
      icon: Fish,
      level: "Moderate",
      bestFor: "Water lovers, couples, friends",
      image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=80",
      summary: "An easy way to add marine life, clear water, and a more active ocean plan to a Cancun stay.",
      highlights: ["Colorful reef areas", "Boat departure options", "Short or half-day formats", "Popular with first-timers"],
    },
    {
      title: "Archaeology and culture day",
      category: "History + sightseeing",
      time: "Full day",
      icon: MountainSnow,
      level: "Moderate",
      bestFor: "Culture-focused travelers, first-time Mexico visitors",
      image: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1200&q=80",
      summary: "A bigger day focused on archaeology, local history, and classic Yucatán landmarks paired with scenic stops.",
      highlights: ["Historic sites", "Longer excursion", "Great for first visits", "Pairs well with cenote stops"],
    },
  ],
  itineraries: [
    {
      title: "Easygoing beach day",
      activityLevel: "Low",
      duration: "1 day",
      pace: "Slow and relaxed",
      items: ["Late breakfast nearby", "Playa Delfines scenic stop", "Pool or quiet afternoon", "Sunset dinner"],
    },
    {
      title: "Water and island day",
      activityLevel: "Medium",
      duration: "1 day",
      pace: "Balanced",
      items: ["Morning ferry or boat ride", "Isla Mujeres beach time", "Optional snorkeling", "Easy return dinner"],
    },
    {
      title: "Cenotes + local evening",
      activityLevel: "Medium",
      duration: "1 day",
      pace: "Active then relaxed",
      items: ["Half-day cenote trip", "Rest at the house", "Casual tacos or seafood dinner", "Easy night out"],
    },
    {
      title: "Adventure-focused day",
      activityLevel: "High",
      duration: "1 day",
      pace: "Full and energetic",
      items: ["Early departure", "Cenotes or reef activity", "Late lunch", "Sunset walk or rooftop drinks"],
    },
    {
      title: "Family-friendly mix",
      activityLevel: "Low to medium",
      duration: "2 days",
      pace: "Flexible",
      items: ["Beach morning", "Pool break", "Easy local food", "Second day island or scenic stop"],
    },
    {
      title: "First-time Cancun sampler",
      activityLevel: "Medium",
      duration: "3 days",
      pace: "Balanced",
      items: ["Beach + scenic walk", "Island or reef day", "Cenote or culture day"],
    },
  ],
  availabilityMonths: [
    { name: "May", statuses: [{ label: "Ocean", value: "Good" }, { label: "Garden", value: "Good" }, { label: "Rooftop", value: "Limited" }] },
    { name: "June", statuses: [{ label: "Ocean", value: "Good" }, { label: "Garden", value: "Limited" }, { label: "Rooftop", value: "Good" }] },
    { name: "July", statuses: [{ label: "Ocean", value: "Limited" }, { label: "Garden", value: "Good" }, { label: "Rooftop", value: "Limited" }] },
    { name: "August", statuses: [{ label: "Ocean", value: "Busy" }, { label: "Garden", value: "Limited" }, { label: "Rooftop", value: "Busy" }] },
    { name: "September", statuses: [{ label: "Ocean", value: "Good" }, { label: "Garden", value: "Good" }, { label: "Rooftop", value: "Good" }] },
  ],
  gallery: [
    "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
  ],
  testimonials: [
    { name: "Sarah (USA)", text: "This felt more personal than a resort. Beautiful stay, smooth booking, and a warm host.", rating: 5 },
    { name: "Luis (Mexico)", text: "Muy cómodo, excelente ubicación y muy buena atención.", rating: 5 },
    { name: "Claire (France)", text: "Peaceful, elegant, and easy to enjoy. We would absolutely stay again.", rating: 5 },
  ],
  faqs: [
    { q: "How do I book a room?", a: "Guests choose dates, select a room, and send a direct booking request through the site or WhatsApp." },
    { q: "Can I ask about airport pickup or local recommendations?", a: "Yes. Extras like airport transfers, local dining tips, and trip ideas can be arranged directly with the host." },
    { q: "Is the site ready for real property details later?", a: "Yes. Photos, room details, policies, and pricing can all be replaced easily once final information is available." },
    { q: "Can this turn into a full booking site later?", a: "Yes. The current structure is a strong base for adding payment, calendar sync, or a more advanced booking system." },
  ],
  bookingPerks: [
    "Direct contact with the host",
    "Simple request flow with no account required",
    "Pricing preview before sending a message",
    "Easy upgrade path for future real-time booking",
  ],
};

export const translations = {
  en: {
    navHome: "Home",
    navRooms: "Rooms",
    navExperiences: "Experiences",
    navItineraries: "Itineraries",
    navBook: "Book",
    directBooking: "Direct booking",
    heroTitle: "A calm, modern tropical stay near Cancun.",
    heroCopy: "Private rooms, thoughtful hosting, and a direct booking experience designed to feel simple from the first click.",
    viewRooms: "View rooms",
    requestBooking: "Request booking",
    startingFrom: "Starting from",
    requestThisRoom: "Book this room",
    roomsTitle: "A room for every kind of stay",
    roomsEyebrow: "Rooms",
    amenitiesEyebrow: "Amenities",
    amenitiesTitle: "Thoughtful comforts, clearly presented",
    galleryEyebrow: "Gallery",
    galleryTitle: "A brighter, cleaner first impression",
    experiencesEyebrow: "Experiences",
    experiencesTitle: "Helpful activity ideas that keep planning simple",
    itinerariesEyebrow: "Itineraries",
    itinerariesTitle: "Suggested days by energy level and travel style",
    reviewsEyebrow: "Guest reviews",
    testimonialsTitle: "What guests say",
    mapEyebrow: "Location",
    locationTitle: "Near Cancun, with easy access to beaches and day trips",
    bookingEyebrow: "Booking",
    bookingTitle: "Choose your dates and request your stay",
    chooseDates: "Choose dates",
    pickRoom: "Pick a room",
    confirmFast: "Quick confirmation",
    requestStay: "Booking request",
    fullName: "Full name",
    email: "Email",
    checkIn: "Check-in",
    checkOut: "Check-out",
    questions: "Questions or special requests",
    sendBooking: "Send request",
    lengthOfStay: "Length of stay",
    estimatedTotal: "Estimated total",
    night: "night",
    nights: "nights",
    footerTag: "Direct booking. Clear details. Easy planning.",
    backToTop: "Back to top",
  },
};
