import {
  Wifi,
  Waves,
  Coffee,
  Car,
  ShieldCheck,
  Sun,
  Users,
  Heart,
  Baby,
  Compass,
  Plane,
  MapPin,
  Clock3,
  BedDouble,
  Calendar,
  PalmTree,
} from "lucide-react";

export const siteData = {
  brand: {
    name: "Casa Brisa del Mar",
    locationShort: "Near Cancun, Mexico",
    tagline: "Modern tropical stays near Cancun",
    whatsappNumber: "+52 998 000 0000",
    email: "hello@casabrisadelmar.com",
  },
  currencies: {
    USD: { symbol: "$", rate: 1, label: "USD" },
    MXN: { symbol: "$", rate: 16.7, label: "MXN" },
    EUR: { symbol: "€", rate: 0.92, label: "EUR" },
    CAD: { symbol: "C$", rate: 1.36, label: "CAD" },
    GBP: { symbol: "£", rate: 0.79, label: "GBP" },
    BRL: { symbol: "R$", rate: 4.95, label: "BRL" },
  },
  supportedLanguages: [
    { code: "en", label: "English" },
    { code: "es", label: "Español" },
    { code: "fr", label: "Français" },
    { code: "pt", label: "Português" },
  ],
  heroImages: [
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1600&q=80",
    "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1600&q=80",
  ],
  heroStats: [
    { value: "3", label: "Private rooms" },
    { value: "10 min", label: "From the beach" },
    { value: "Direct", label: "Book with the host" },
  ],
  specials: [
    { badge: "Popular", title: "Direct booking rates" },
    { badge: "Extended stays", title: "Weekly stay options" },
    { badge: "Add-ons", title: "Airport pickup available" },
  ],
  amenities: [
    { label: "High-speed Wi-Fi", icon: Wifi },
    { label: "Private pool", icon: Waves },
    { label: "Breakfast included", icon: Coffee },
    { label: "Free parking", icon: Car },
    { label: "Safe & secure", icon: ShieldCheck },
    { label: "Sunny Caribbean vibe", icon: Sun },
  ],
  rooms: [
    {
      id: "room-1",
      name: "The Ocean Room",
      priceUSD: 85,
      sleeps: "2 guests",
      bed: "1 King bed",
      size: "28 m²",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
      features: ["Private terrace", "Ocean view", "Rain shower", "Air conditioning"],
      status: "Available",
      badge: "Most popular",
      descriptions: {
        en: "Wake up to soft ocean breezes, a bright interior, and a private terrace with a relaxed coastal feel.",
        es: "Despierta con brisas suaves del mar, un interior luminoso y una terraza privada con ambiente costero.",
        fr: "Réveillez-vous avec une douce brise marine, un intérieur lumineux et une terrasse privée à l’esprit côtier.",
        pt: "Acorde com a brisa do mar, um interior iluminado e um terraço privativo com clima litorâneo.",
      },
    },
    {
      id: "room-2",
      name: "The Garden Suite",
      priceUSD: 110,
      sleeps: "4 guests",
      bed: "1 King + 1 sofa bed",
      size: "42 m²",
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80",
      features: ["Pool access", "Garden view", "Kitchenette", "Extra space"],
      status: "Available",
      badge: "Best for families",
      descriptions: {
        en: "A larger suite framed by tropical greenery, ideal for families and longer stays with extra comfort.",
        es: "Una suite amplia rodeada de vegetación tropical, ideal para familias y estancias más largas.",
        fr: "Une suite spacieuse entourée de verdure tropicale, idéale pour les familles et les séjours plus longs.",
        pt: "Uma suíte ampla cercada por verde tropical, ideal para famílias e estadias mais longas.",
      },
    },
    {
      id: "room-3",
      name: "The Rooftop Loft",
      priceUSD: 95,
      sleeps: "2 guests",
      bed: "1 Queen bed",
      size: "32 m²",
      image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=80",
      features: ["Private rooftop", "Open-air feel", "Premium linens", "Hammock"],
      status: "Available",
      badge: "Most romantic",
      descriptions: {
        en: "An intimate top-floor retreat with a private rooftop setting made for slower mornings and sunset evenings.",
        es: "Un refugio íntimo en la parte superior con un espacio privado en la azotea para mañanas lentas y atardeceres.",
        fr: "Un refuge intime au dernier étage avec un espace rooftop privé, parfait pour les matins calmes et les couchers de soleil.",
        pt: "Um refúgio íntimo no último andar com espaço privativo no rooftop, perfeito para manhãs tranquilas e fins de tarde.",
      },
    },
  ],
  travelerTypes: [
    { title: "Solo trips", icon: Compass, copy: "Quiet, personal, and easy to navigate." },
    { title: "Couples", icon: Heart, copy: "A relaxed setting for beach mornings and sunset dinners." },
    { title: "Family trips", icon: Baby, copy: "Room options and outdoor space that make family stays easier." },
    { title: "Small groups", icon: Users, copy: "A comfortable base for shared stays near Cancun." },
  ],
  attractions: [
    { name: "Nearby beaches", type: "Beach", time: "5–15 min", copy: "Easy beach access for swimming, relaxing, and sunset walks.", icon: Waves },
    { name: "Downtown Cancun dining", type: "Food & nightlife", time: "15–25 min", copy: "Local restaurants, tacos, cafés, and nightlife.", icon: Coffee },
    { name: "Isla Mujeres ferry", type: "Day trip", time: "20–30 min", copy: "An easy add-on for snorkeling, beach clubs, and an island day out.", icon: Plane },
    { name: "Cenotes & nature spots", type: "Adventure", time: "30–60 min", copy: "A memorable Yucatán experience for nature-focused travelers.", icon: Sun },
    { name: "Shopping & essentials", type: "Convenience", time: "10–20 min", copy: "Groceries, pharmacies, and everything needed for an easy stay.", icon: MapPin },
    { name: "Airport access", type: "Travel", time: "25–40 min", copy: "Convenient arrivals for weekend breaks or longer stays.", icon: Clock3 },
  ],
  availabilityMonths: [
    { name: "May", statuses: [{ label: "Ocean", value: "Good" }, { label: "Garden", value: "Good" }, { label: "Rooftop", value: "Limited" }] },
    { name: "June", statuses: [{ label: "Ocean", value: "Good" }, { label: "Garden", value: "Limited" }, { label: "Rooftop", value: "Good" }] },
    { name: "July", statuses: [{ label: "Ocean", value: "Limited" }, { label: "Garden", value: "Good" }, { label: "Rooftop", value: "Limited" }] },
    { name: "August", statuses: [{ label: "Ocean", value: "Busy" }, { label: "Garden", value: "Limited" }, { label: "Rooftop", value: "Busy" }] },
    { name: "September", statuses: [{ label: "Ocean", value: "Good" }, { label: "Garden", value: "Good" }, { label: "Rooftop", value: "Good" }] },
  ],
  subPages: [
    { title: "Rooms", copy: "A dedicated page for room details, photos, and rates.", cta: "View page", href: "#rooms", icon: BedDouble },
    { title: "Experiences", copy: "Showcase beach days, island trips, cenotes, and curated add-ons.", cta: "Explore", href: "#attractions", icon: PalmTree },
    { title: "Availability", copy: "A future page for calendar-based availability and direct booking requests.", cta: "See availability", href: "#booking", icon: Calendar },
  ],
  gallery: [
    "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=900&q=80",
    "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=80",
  ],
  testimonials: [
    { name: "Sarah (USA)", text: "This felt more personal than a resort. Beautiful stay, smooth booking, and a warm host.", rating: 5 },
    { name: "Luis (Mexico)", text: "Muy cómodo, excelente ubicación y muy buena atención.", rating: 5 },
    { name: "Claire (France)", text: "Peaceful, elegant, and easy to enjoy. We would absolutely stay again.", rating: 5 },
  ],
};

export const translations = {
  en: {
    navRooms: "Rooms",
    navGallery: "Gallery",
    navAttractions: "Attractions",
    navReviews: "Reviews",
    navLocation: "Location",
    navBook: "Book",
    directBooking: "Direct booking",
    heroTitle: "A calm, modern tropical stay near Cancun.",
    heroCopy: "Private rooms, thoughtful hosting, and a direct booking experience designed to feel simple from the first click.",
    viewRooms: "View rooms",
    requestBooking: "Request booking",
    roomsEyebrow: "Rooms",
    roomsTitle: "A room for every kind of stay",
    startingFrom: "Starting from",
    requestThisRoom: "Book this room",
    amenitiesEyebrow: "Amenities",
    amenitiesTitle: "Thoughtful comforts, clearly presented",
    galleryEyebrow: "Gallery",
    galleryTitle: "A brighter, cleaner first impression",
    tripEyebrow: "Stay styles",
    tripTitle: "Designed for different kinds of travelers",
    attractionsEyebrow: "Nearby",
    attractionsTitle: "The best of Cancun and the coast, within easy reach",
    pagesEyebrow: "More to explore",
    pagesTitle: "Future sections ready to expand",
    availabilityEyebrow: "Availability",
    availabilityTitle: "A quick availability snapshot",
    reviewsEyebrow: "Guest reviews",
    testimonialsTitle: "What guests say",
    mapEyebrow: "Location",
    locationTitle: "Near Cancun, with easy access to beaches and day trips",
    bookingEyebrow: "Booking",
    bookingTitle: "Choose your dates and request your stay",
    chooseDates: "Choose dates",
    pickRoom: "Pick a room",
    confirmFast: "Quick confirmation",
    requestStay: "Booking request",
    fullName: "Full name",
    email: "Email",
    checkIn: "Check-in",
    checkOut: "Check-out",
    selectRoom: "Select a room",
    questions: "Questions or special requests",
    sendBooking: "Send request",
    lengthOfStay: "Length of stay",
    estimatedTotal: "Estimated total",
    night: "night",
    nights: "nights",
    footerTag: "Direct booking. Clear details. Easy planning.",
    backToTop: "Back to top",
  },
  es: {
    navRooms: "Habitaciones",
    navGallery: "Galería",
    navAttractions: "Atracciones",
    navReviews: "Reseñas",
    navLocation: "Ubicación",
    navBook: "Reservar",
    directBooking: "Reserva directa",
    heroTitle: "Una estadía tropical tranquila y moderna cerca de Cancún.",
    heroCopy: "Habitaciones privadas, atención cuidada y una experiencia de reserva directa pensada para sentirse simple desde el primer clic.",
    viewRooms: "Ver habitaciones",
    requestBooking: "Solicitar reserva",
    roomsEyebrow: "Habitaciones",
    roomsTitle: "Una habitación para cada tipo de viaje",
    startingFrom: "Desde",
    requestThisRoom: "Reservar habitación",
    amenitiesEyebrow: "Servicios",
    amenitiesTitle: "Comodidades pensadas con claridad",
    galleryEyebrow: "Galería",
    galleryTitle: "Una primera impresión más limpia y luminosa",
    tripEyebrow: "Tipos de estancia",
    tripTitle: "Diseñado para diferentes viajeros",
    attractionsEyebrow: "Cerca",
    attractionsTitle: "Lo mejor de Cancún y la costa, al alcance",
    pagesEyebrow: "Más para explorar",
    pagesTitle: "Secciones futuras listas para crecer",
    availabilityEyebrow: "Disponibilidad",
    availabilityTitle: "Una vista rápida de disponibilidad",
    reviewsEyebrow: "Reseñas",
    testimonialsTitle: "Lo que dicen los huéspedes",
    mapEyebrow: "Ubicación",
    locationTitle: "Cerca de Cancún, con acceso fácil a playas y paseos",
    bookingEyebrow: "Reserva",
    bookingTitle: "Elige tus fechas y solicita tu estancia",
    chooseDates: "Elegir fechas",
    pickRoom: "Elegir habitación",
    confirmFast: "Confirmación rápida",
    requestStay: "Solicitud de reserva",
    fullName: "Nombre completo",
    email: "Correo electrónico",
    checkIn: "Entrada",
    checkOut: "Salida",
    selectRoom: "Selecciona una habitación",
    questions: "Preguntas o solicitudes especiales",
    sendBooking: "Enviar solicitud",
    lengthOfStay: "Duración de la estancia",
    estimatedTotal: "Total estimado",
    night: "noche",
    nights: "noches",
    footerTag: "Reserva directa. Información clara. Plan fácil.",
    backToTop: "Volver arriba",
  },
  fr: {
    navRooms: "Chambres",
    navGallery: "Galerie",
    navAttractions: "Attractions",
    navReviews: "Avis",
    navLocation: "Emplacement",
    navBook: "Réserver",
    directBooking: "Réservation directe",
    heroTitle: "Un séjour tropical calme et moderne près de Cancún.",
    heroCopy: "Chambres privées, accueil attentionné et expérience de réservation directe pensée pour rester simple dès le premier clic.",
    viewRooms: "Voir les chambres",
    requestBooking: "Demander une réservation",
    roomsEyebrow: "Chambres",
    roomsTitle: "Une chambre pour chaque style de séjour",
    startingFrom: "À partir de",
    requestThisRoom: "Réserver cette chambre",
    amenitiesEyebrow: "Services",
    amenitiesTitle: "Des conforts bien pensés, présentés clairement",
    galleryEyebrow: "Galerie",
    galleryTitle: "Une première impression plus lumineuse et plus nette",
    tripEyebrow: "Styles de séjour",
    tripTitle: "Pensé pour différents types de voyageurs",
    attractionsEyebrow: "À proximité",
    attractionsTitle: "Le meilleur de Cancún et de la côte à portée de main",
    pagesEyebrow: "À découvrir",
    pagesTitle: "Des sections futures prêtes à évoluer",
    availabilityEyebrow: "Disponibilité",
    availabilityTitle: "Un aperçu rapide des disponibilités",
    reviewsEyebrow: "Avis",
    testimonialsTitle: "Ce que disent les voyageurs",
    mapEyebrow: "Emplacement",
    locationTitle: "Près de Cancún, avec un accès facile aux plages et excursions",
    bookingEyebrow: "Réservation",
    bookingTitle: "Choisissez vos dates et demandez votre séjour",
    chooseDates: "Choisir les dates",
    pickRoom: "Choisir une chambre",
    confirmFast: "Confirmation rapide",
    requestStay: "Demande de réservation",
    fullName: "Nom complet",
    email: "E-mail",
    checkIn: "Arrivée",
    checkOut: "Départ",
    selectRoom: "Choisissez une chambre",
    questions: "Questions ou demandes spéciales",
    sendBooking: "Envoyer la demande",
    lengthOfStay: "Durée du séjour",
    estimatedTotal: "Total estimé",
    night: "nuit",
    nights: "nuits",
    footerTag: "Réservation directe. Informations claires. Planification simple.",
    backToTop: "Haut de page",
  },
  pt: {
    navRooms: "Quartos",
    navGallery: "Galeria",
    navAttractions: "Atrações",
    navReviews: "Avaliações",
    navLocation: "Localização",
    navBook: "Reservar",
    directBooking: "Reserva direta",
    heroTitle: "Uma estadia tropical calma e moderna perto de Cancún.",
    heroCopy: "Quartos privativos, atendimento atencioso e uma experiência de reserva direta pensada para ser simples desde o primeiro clique.",
    viewRooms: "Ver quartos",
    requestBooking: "Solicitar reserva",
    roomsEyebrow: "Quartos",
    roomsTitle: "Um quarto para cada tipo de estadia",
    startingFrom: "A partir de",
    requestThisRoom: "Reservar este quarto",
    amenitiesEyebrow: "Comodidades",
    amenitiesTitle: "Confortos bem pensados, apresentados com clareza",
    galleryEyebrow: "Galeria",
    galleryTitle: "Uma primeira impressão mais limpa e luminosa",
    tripEyebrow: "Tipos de estadia",
    tripTitle: "Pensado para diferentes tipos de viajantes",
    attractionsEyebrow: "Por perto",
    attractionsTitle: "O melhor de Cancún e da costa ao seu alcance",
    pagesEyebrow: "Mais para explorar",
    pagesTitle: "Seções futuras prontas para crescer",
    availabilityEyebrow: "Disponibilidade",
    availabilityTitle: "Uma visão rápida da disponibilidade",
    reviewsEyebrow: "Avaliações",
    testimonialsTitle: "O que os hóspedes dizem",
    mapEyebrow: "Localização",
    locationTitle: "Perto de Cancún, com fácil acesso a praias e passeios",
    bookingEyebrow: "Reserva",
    bookingTitle: "Escolha suas datas e solicite sua estadia",
    chooseDates: "Escolher datas",
    pickRoom: "Escolher quarto",
    confirmFast: "Confirmação rápida",
    requestStay: "Solicitação de reserva",
    fullName: "Nome completo",
    email: "E-mail",
    checkIn: "Check-in",
    checkOut: "Check-out",
    selectRoom: "Selecione um quarto",
    questions: "Perguntas ou pedidos especiais",
    sendBooking: "Enviar solicitação",
    lengthOfStay: "Duração da estadia",
    estimatedTotal: "Total estimado",
    night: "noite",
    nights: "noites",
    footerTag: "Reserva direta. Informações claras. Planejamento fácil.",
    backToTop: "Voltar ao topo",
  },
};
